# Generated by Django 4.0.5 on 2022-07-02 05:33

import NFSDATA.formatchecker
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_details', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('cateogry_details', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('product_cost_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('product_image', NFSDATA.formatchecker.ContentRestrictiononFileField(default=None, upload_to='products/')),
                ('product_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('product_age_groups', models.CharField(choices=[('INFANTS', 'Below 5'), ('MID_INFANTS', '6-15'), ('TEENAGER', '16-24'), ('WORKING', '25-55'), ('DEPENDENTS', 'Over 56')], max_length=30)),
                ('product_minicategory', models.CharField(blank=True, default=None, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateField()),
                ('product_brand', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NFSDATA.brands')),
                ('product_category', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NFSDATA.category')),
            ],
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('size_code', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=255)),
                ('sub_cat_details', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoldProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_selling_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('product_amount_sold', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('added_date', models.DateField()),
                ('product_sold', models.ForeignKey(default='Sold Item', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='NFSDATA.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_size',
            field=models.ManyToManyField(to='NFSDATA.sizecategory'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_subcategory',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NFSDATA.subcategory'),
        ),
    ]
