# Generated by Django 4.0.5 on 2022-07-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFSDATA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_age_groups',
            field=models.CharField(choices=[('INFANTS', 'Below 5'), ('MID_INFANTS', '6-10'), ('TEENAGER', '11-18'), ('WORKING', '19-55'), ('DEPENDENTS', 'Over 56')], max_length=30),
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_no', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('billing_date', models.DateField(auto_now=True)),
                ('customer_detail', models.CharField(max_length=255)),
                ('customer_contact', models.CharField(max_length=15)),
                ('items', models.ManyToManyField(to='NFSDATA.soldproducts')),
            ],
        ),
    ]
